openapi: 3.0.3

info:
  version: 0.0.1
  title: Randstadgroep Nederland, supplier management
  description: |

paths:

  /api/contracts:
    post:
      tags:
        - contracting
      summary: Starts the contracting supplier process.
      operationId: ContractSupplierV1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "../data-dictionary/commands/contract_supplier.yml"
      responses:
        201:
          $ref: "../../../data-dictionary/responses/201.yml"
        400:
          $ref: "../../../data-dictionary/responses/400.yml"
        401:
          $ref: "../../../data-dictionary/responses/401.yml"
        403:
          $ref: "../../../data-dictionary/responses/403.yml"