openapi: 3.0.3

info:
  version: 0.0.1
  title: Randstadgroep Nederland, timesheet management
  description: |

paths:

  /api/hours:
    get:
      parameters:
        - $ref: "../../get-qualified-talent/data-dictionary/parameters/query/talent_id.yml"
        - $ref: "../../manage-employment/data-dictionary/parameters/query/payrolling_period.yml"
        - $ref: "../../data-dictionary/parameters/query/year.yml"
        - $ref: "../data-dictionary/parameters/query/assignment_id_collection.yml"
      tags:
        - hours
      summary: Gets an approved hours collection by period.
      operationId: GetPeriodHoursV1
      responses:
        200:          
          description: OK
          content:
            application/json:
              schema:
                $ref: "./data-dictionary/responses/period_hours.yml"
        400:
          $ref: "../../data-dictionary/responses/400.yml"
        401:
          $ref: "../../data-dictionary/responses/401.yml"
        403:
          $ref: "../../data-dictionary/responses/403.yml"