openapi: 3.0.3

info:
  version: 0.0.1
  title: Randstadgroep Nederland, timesheet management
  description: |

paths:

  /api/labor-contracts/{labor_contract_id}:
    get:
      parameters:
        - $ref: "./data-dictionary/parameters/path/labor_contract_id.yml"
      tags:
        - labor contract
      summary: Gets a labor contract instance.
      operationId: GetLaborContractV1
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "./data-dictionary/responses/labor_contract.yml"
        400:
          $ref: "../../data-dictionary/responses/400.yml"
        401:
          $ref: "../../data-dictionary/responses/401.yml"
        403:
          $ref: "../../data-dictionary/responses/403.yml"
        404:
          $ref: "../../data-dictionary/responses/404.yml"