name: npm audit

on:
  
  workflow_dispatch:    

  pull_request:
    types: [opened,synchronize]
    
  schedule:
    - cron: '0 0 * * *'

jobs:
  
  audit:
    
    name: npm audit
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - uses: actions/checkout@v2
      
      - name: install dependencies
        run: npm ci

      - name: audit
        uses: oke-py/npm-audit-action@v1.8.2
        with:
          audit_level: high
          github_token: ${{ github.token }}
          issue_assignees: arjangeertsema
          issue_labels: vulnerability,test
          dedupe_issues: true
