name: release

on:
  
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  
  release:
  
    runs-on: ubuntu-latest
    environment: production
    if: github.event.pull_request.merged
    timeout-minutes: 5
  
    steps:
  
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
        
      - name: get package version
        id: package-version
        uses: Saionaro/extract-package-version@v1.0.6

      - name: print package version
        run: |
          echo 'package version: ${{ steps.package-version.outputs.version }}'

      - name: get tag version
        id: tag-version
        uses: WyriHaximus/github-action-get-previous-tag@v1

      - name: print tag version
        run: |
          echo 'tag version: ${{ steps.tag-version.outputs.tag }}'          
  
      - uses: actions/setup-node@v2
        if: steps.package-version.outputs.version != steps.tag-version.outputs.tag
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
  
      - run: npm ci
        if: steps.package-version.outputs.version != steps.tag-version.outputs.tag
        
      - run: rm -rf tests
        if: steps.package-version.outputs.version != steps.tag-version.outputs.tag
  
      - run: npm publish --access public
        if: steps.package-version.outputs.version != steps.tag-version.outputs.tag
        env:
          VERSION: ${{ steps.package-version.outputs.version}}
          NODE_AUTH_TOKEN: ${{ secrets.NPM }}

      - uses: actions-ecosystem/action-push-tag@v1
        if: steps.package-version.outputs.version != steps.tag-version.outputs.tag
        with:
          tag: ${{ steps.package-version.outputs.version}}
          message: 'Version ${{ steps.package-version.outputs.version}}: PR #${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }}'