name: release

on:
  
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  
  build:
  
    runs-on: ubuntu-latest
    environment: production    
    if: github.event.pull_request.merged
  
    steps:
  
      - uses: actions/checkout@v2
  
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
  
      - run: npm ci
        
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
        
      - run: rm-rf tests
  
      - run: npm publish --access public
        env:
          VERSION: ${{ steps.package-version.outputs.current-version}}
          NODE_AUTH_TOKEN: ${{ secrets.NPM }}

      - uses: actions-ecosystem/action-push-tag@v1
        with:
          tag: ${{ steps.package-version.outputs.current-version}}
          message: '${{ ${{ steps.package-version.outputs.current-version}} }}: PR #${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }}'