name: test

on:
  
  pull_request:
    types: [opened,synchronize]

jobs:
  
  build:
    
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == false
    timeout-minutes: 5
  
    steps:
      
      - uses: actions/checkout@v2
        
      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Install
        run: npm ci

      - name: Build branches
        working-directory: tests
        id: branches
        run: |
          node ../bin/index.js -b
          BRANCHES=$(cat ./dist/branches.json)
          echo "::set-output name=value::${BRANCHES//'%'/'%25'}"

      - name: Build websites
        working-directory: tests
        shell: bash
        run: |
          git fetch
          for B in $(echo $BRANCHES | jq -r 'sort_by(.path) | .[].name')
          do
              git checkout "$B"
              npm ci
              node ../bin/index.js
          done
        env:
          BRANCHES: ${{ steps.branches.outputs.value }}