name: test

on:
  
  pull_request:
    types: [opened,synchronize]

jobs:
  
  build:
    
    runs-on: ubuntu-22.04
    if: github.event.pull_request.merged == false
    timeout-minutes: 5
  
    steps:
      
      - uses: actions/checkout@v2
        
      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: Install
        run: |
          npm ci

      - name: Build
        working-directory: tests
        run: |
          node ../bin/index.js -f