name: test

on:
  
  pull_request:
    types: [opened,synchronize]

jobs:
  
  build:
    
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == false
    timeout-minutes: 5
  
    steps:
      
      - uses: actions/checkout@v2
        
      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: Install PrinceXml
        run: |
          wget http://archive.ubuntu.com/ubuntu/pool/universe/liba/libavif/libavif16_1.0.4-1ubuntu3_amd64.deb
          sudo dpkg -i libavif16_1.0.4-1ubuntu3_amd64.deb

          wget http://archive.ubuntu.com/ubuntu/pool/main/g/giflib/libgif7_5.1.9-2ubuntu0.1_amd64.deb
          sudo dpkg -i libgif7_5.1.9-2ubuntu0.1_amd64.deb
          
          wget https://www.princexml.com/download/prince_20241206-1_ubuntu24.04_amd64.deb
          sudo dpkg -i prince_20241206-1_ubuntu24.04_amd64.deb

      - name: Install md-docs
        run: |
          npm ci       

      - name: Build
        working-directory: tests
        run: |
          node ../bin/index.js -f