name: test

on:
  
  pull_request:
    types: [opened,synchronize]

jobs:
  
  build:
    
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == false
    timeout-minutes: 5
  
    steps:
      
      - uses: actions/checkout@v2

      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: Install md-docs
        run: |
          npm i

      - name: Install PrinceXml
        run: |
          sudo apt-get install libgif7
          sudo apt-get install libavif16
          node node_modules/@biz-dev-ops/md-docs/node_modules/prince/prince-npm.js install

      - name: Build
        working-directory: tests
        run: |
          node ../bin/index.js -f